fetcher:
  tushare_token: "${TUSHARE_TOKEN}"

store:
  access_key_id: "${R2_ACCESS_KEY_ID}"
  secret_access_key: "${R2_SECRET_ACCESS_KEY}"
  bucket_name: "${R2_BUCKET_NAME}"
  bucket_endpoint: "${R2_ENDPOINT}"

meta:
  meta_collection_name: "${FIREBASE_COLLECTION_NAME}"
